version: "3"
services:
  search-engine:
    image: ./servers/search-engine
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017/search-engine
      - PORT=8080
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
